config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :announcements
    resources :notifications
    resources :services
    resources :users

    root to: "users#index"
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "/menu", to: "menu#new"
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  resources :announcements, only: [:index]
  resources :meals
  resources :notifications, only: [:index]

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user

  has_rich_text :description
  has_one_attached :header_image
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = current_user.meals.all.order(:id)
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = current_user.meals.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = current_user.meals.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meals_url, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to meals_url, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = current_user.meals.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :header_image, :description)
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', autofocus: true %>
  </div>

  <div class="form-group">
    <div class="custom-file">
      <%= form.file_field :header_image, class: 'custom-file-input' %>
      <%= form.label :header_image, 'Choose file', class: 'custom-file-label' %>
    </div>
  </div>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if meal.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', meal, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if meal.persisted? %>
      <%= link_to "Cancel", meal, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", meals_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/meals/_table_row.html.erb
<td><%= image_tag meal.header_image.variant(resize_to_limit: [48, 48]) if meal.header_image.attached? %></td>
<td><%= link_to meal.name, meal %></td>
<td><%= meal.description.to_plain_text.truncate(100) %></td>

app/views/meals/edit.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <h1>Edit Meal</h1>

    <%= render 'form', meal: @meal %>
  </div>
</div>

app/views/meals/index.html.erb
<div class="page-header">
  <h1>Meals</h1>
  <div>
    <%= link_to new_meal_path, class: 'btn btn-primary' do %>
      <%= icon('fas', 'plus-circle') %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th style="width: 52px"></th>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <% @meals.each do |meal| %>
        <%= content_tag :tr, id: dom_id(meal), class: dom_class(meal) do %>
          <%= render partial: "table_row", locals: { meal: meal } %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meals/new.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <h1>New meal</h1>

    <%= render 'form', meal: @meal %>
  </div>
</div>

app/views/meals/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="page-header">
      <h1><%= @meal.name %></h1>
      <div>
        <%= link_to meals_path, class: 'btn btn-primary' do %>
          <%= icon("fas", "chevron-circle-left") %>
        <% end %>
        <%= link_to edit_meal_path(@meal), class: 'btn btn-success' do %>
          <%= icon("fas", "edit") %>
        <% end %>
      </div>
    </div>

    <div class="header-image">
      <%= image_tag @meal.header_image.variant(resize_to_limit: [200, 200]) if @meal.header_image.attached? %>
    </div>

    <div class="meal-description">
      <%= @meal.description %>
    </div>
  </div>
</div>